### ISSUE TITLE
Will it work for ESP 12 module?

### ISSUE THREAD

**Issue by Sumgit91** [NaoNaoMe/Uart-WiFi-Board#1]
Hi iam using ESP12 module and i need to transmit data from a sensor module which transmits data serially to appear in an interactive web page (which should act like a terminal program), will this code work for me?

**Comment by NaoNaoMe** [comment]
If you connect esp-module to your sensor module, this code is not appropriate.
Almost all sensor modules communicate with I2C or SPI interface. This project only provide a UART interface.
